0831/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

0831/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('new/', views.new, name='new'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update', views.update, name='update'),
    path('<int:pk>/delete', views.delete, name='delete'),
]

0831/yhjhs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

0831/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

0831/articles/models.py
from django.db import models
from django.forms import CharField, DateTimeField, IntegerField

# Create your models here.

class articleModel(models.Model):
    name = models.CharField(max_length=10)
    age = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)

0831/accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        
class CustomUserChangeForm(UserChangeForm):
    
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'date_joined')

0831/articles/forms.py
from dataclasses import field
from re import A
from django import forms
from django import forms
from .models import articleModel

class ArticleForm(forms.ModelForm):
    name = forms.CharField(
        label='이름',
        widget=forms.TextInput(
            attrs={
                'class': '내 이름',
                'placeholder': '이름을 입력하세요',
                'maxlength': 10,
            }
        ),
        error_messages={
            'required': '이름을 꼭 입력하세요'
        }
    )
    age = forms.IntegerField(
        label='나이',
        widget=forms.NumberInput(
            attrs={
                'placeholder': '나이를 입력하세요',
            }
        ),
        error_messages={
            'required': '나이를 꼭 입력하세요'
        }
    )
    
    class Meta:
        model = articleModel
        fields = '__all__'

0831/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('articles:index')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('articles:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

0831/articles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import articleModel
from .forms import ArticleForm

import articles

# Create your views here.

@require_safe
def index(request):
    articles = articleModel.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)

# def new(request):
#     form = ArticleForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'articles/new.html', context)

@require_safe
def detail(request, pk):
    article = articleModel.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)
    
# def edit(request, pk):
#     article = articleModel.objects.get(pk=pk)
#     form = ArticleForm(instance=article)
#     context = {
#         'article': article,
#         'form': form,
#     }
    
#     return render(request, 'articles/edit.html', context)

@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = articleModel.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'article': article,
        'form': form,
    }
    
    return render(request, 'articles/update.html', context)

@require_POST
def delete(request, pk):
    article = articleModel.objects.get(pk=pk)
    article.delete()
    
    return redirect('articles:index')
    

0831/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
  <h1>로그인</h1>
  <form action="{% url 'accounts:login' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
  </form>
{% endblock content %}

0831/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
  <h1>회원가입</h1>
  <form action="{% url 'accounts:signup' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="회원가입">
  </form>
{% endblock content %}

0831/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>수정 페이지</h1>
  <form action="{% url 'accounts:update' %}" method='POST'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="수정하기">
  </form>
{% endblock content %}

0831/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>새로 만들기</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">처음으로 가기</a>
{% endblock content %}

0831/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>세부 사항</h2>
  <p>{{ article.name }}</p>
  <p>{{ article.age }}</p>
  <p>{{ article.date }}</p>
  <a href="{% url 'articles:update' article.pk %}">수정하기</a>
  <form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="삭제">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">뒤로 가기</a>
{% endblock content %}

0831/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
  <h2>수정하기</h2>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    <label for="name">이름: </label>
    <input type="text" name="name" value="{{ article.name }}"><br>
    <label for="age">나이: </label>
    <textarea name="age" cols="30" rows="5">{{ article.age }}</textarea>
    <input type="submit">
  </form>
{% endblock content %}

0831/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>첫 페이지</h2>
  <a href="{% url 'articles:create' %}">새로 만들기</a>
  <hr>
  {% for article in articles %}
    <a href="{% url 'articles:detail' article.pk %}">세부사항</a>
    {{ article.name }}
    <br>
    {{ article.age }}
    <br>
    {{ article.date }}
    <hr>
  {% endfor %}
{% endblock content %}

0831/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>새로 만들기</h1>
  <form action="{% url 'articles:create' %}" method="POST">
    {% csrf_token %}
    <label for="name">이름: </label>
    <input type="text" name="name"><br>
    <label for="age">나이: </label>
    <textarea name="age" cols="30" rows="5"></textarea><br>
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'articles:index' %}">처음으로 가기</a>
{% endblock content %}

0831/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
  <h2>수정하기</h2>
  <form action="{% url 'articles:update' article.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
{% endblock content %}

0831/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <div class="containter">
    <h3>안녕, {{ user }}</h3>
    <a href="{% url 'accounts:login' %}">로그인</a>
    <hr>
    <form action="{% url 'accounts:logout' %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="로그아웃">
    </form>
    <hr>
    <a href="{% url 'accounts:signup' %}">회원가입</a>
    <hr>
    <form action="{% url 'accounts:delete' %}" method='POST'>
      {% csrf_token %}
      <input type="submit" value="회원탈퇴">
    </form>
    <hr>
    <a href="{% url 'accounts:update' %}">회원정보 수정</a>
    <hr>
    {% block content %}
    {% endblock content %}
  </div>
</body>
</html>