0830/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
]

0830/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'
urlpatterns = [

]

0830/yhjhs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

0830/articles/models.py
from django.db import models

# Create your models here.

0830/pages/models.py
from django.db import models

# Create your models here.

0830/articles/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'articles/index.html')

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {
        'message': message
    }
    return render(request, 'articles/catch.html', context)

0830/pages/views.py
from django.shortcuts import render

# Create your views here.

0830/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h2>잡았다</h2>
  뭘 잡았어
  {{ message }}
{% endblock content %}

0830/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h2>테스트</h2>
{% endblock content %}

0830/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h2>던지기</h2>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">던지기</label>
    <input type="text" name="message" id="message"><br>
    <input type="submit">
  </form>
{% endblock content %}

0830/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {% block content %}
  {% endblock content %}
</body>
</html>